site_name: Rojo Documentation
site_url: https://lpghatguy.github.io/rojo/0.4.x
repo_name: LPGhatguy/rojo
repo_url: https://github.com/LPGhatguy/rojo

theme:
  name: material
  palette:
    primary: 'Red'
    accent: 'Red'

nav:
  - Home: index.md
  - Why Rojo?: why-rojo.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Creating a Project: getting-started/creating-a-project.md
  - Sync Details: sync-details.md

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true