[package]
name = "rojo"
version = "0.4.12"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
description = "A tool to create robust Roblox projects"
license = "MIT"
repository = "https://github.com/LPGhatguy/rojo"

[[bin]]
name = "rojo"
path = "src/bin.rs"

[dependencies]
clap = "2.27.1"
rouille = "2.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
notify = "4.0.0"
rand = "0.3"
regex = "0.2"
lazy_static = "1.0"
